Repository abel-otegbola/clock-app, pull requests merged in 2022-10, with the labels that each got.

#24 Add kids theme
  assets/css/theme.css
  assets/imgs/kids.png
  index.html
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#27 added-pizza-theme
  assets/css/theme.css
  assets/imgs/pizza.png
  index.html
Labels: enhancement, Hacktoberfest

#28 Marble theme added
  assets/css/theme.css
  index.html
  screenshots/11.png.png
Labels: enhancement, Hacktoberfest

#58 Added The Bricks Theme Based On #41
  assets/css/theme.css
  assets/imgs/red-bricks.jpg
  index.html
Labels: hacktoberfest-accepted

#61 added new clock
  assets/css/theme.css
  index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#64 made some design changes and fixed navbar in mobile version
  assets/css/darkmode.css
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#71 Logo added
  assets/css/style.css
  assets/imgs/logo.png
  index.html
Labels: hacktoberfest-accepted
